# Generated by Django 6.0.8 on 2026-10-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=120)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UBS',
                'verbose_name_plural': 'UBSs',
                'ordering': ['nome'],
            },
        ),
    ]
