# Generated by Django 6.0.8 on 2026-10-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubs',
            name='cnes',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='ubs',
            name='como_usar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ubs',
            name='especialidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ubs',
            name='rpa',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
